### ISSUE TITLE
Quester problem quest status...

### ISSUE THREAD

**Issue by ggirelli** [CitizensDev/Citizens#1031]
Hi, I've created a hunt type quest, where the pg must kill 15 zombie, 15 skeleton, 10 creeper & optionally 15 enderman...
But when somebody accept the quest, doing /quest status doesn't show  this:
0 zombie killed, 15 zombie remaining
0 skeleton killed, 15 skeleton remaining
...
Instead it shows this:
0 monster killed, 15 monster remaining
0 monster killed, 15 monster remaining
...
Which makes the status really hard to be read...
Anyone knows how to fix this?

My Quest.yml is the following:

```
"Incursion":
    texts:
        description: "&b<&3Questo&b> &fUltimamente gli attacchi dei mostri si sono fatti sempre piu' numerosi! Abbiamo bisogno di un valoroso eroe! <br>&3Quest: <g>Incursion, Parte 1 <br>&3Obbiettivo: &bUccidi 15 zombie, 15 Skeleton e 10 Creeper."
        acceptance: "&b<&3Questo&b> &fOh valoroso eroe, difendi la città!!!
            <delay=80>&3Quest: <g>Incursion, Parte 1 &fè iniziata!
            <delay=40><g>Ricorda, che puoi fare &6/quest status <g>per vedere lo stato della quest."
        completion: "&b<&3Questo&b> &fIncredibile! Credevo fossi mmm... già morto... Ehm no,... Scherzo! Ho sempre avuto grande, ehm, fiducia in te... ehm... <br>&bQuest: &bHai ricevuto 150$,"
    repeats: -1
    objectives:
        '0':
            '0':
                type: hunt
                string: 'zombie'
                amount: 15
                optional: False
                message: "&3Quest: &bHai ucciso 15 zombie!"
            '1':
                type: hunt
                string: 'skeleton'
                amount: 15
                optional: False
                message: "&3Quest: &bHai ucciso 15 skeleton!"
            '2':
                type: hunt
                string: 'creeper'
                amount: 10
                optional: False
                message: "&3Quest: &bHai ucciso 10 creeper!"
            '3':
                type: hunt
                string: 'enderman'
                amount: 15
                optional: True
                message: "&3Quest: &bHai ucciso 15 enderman.<br>&6Quest: Hai ricevuto una spada di diamante, complimenti!"
                rewards:
                    '0':
                         type: item
                         id: 276  # diamond_sword
                         amount: 1
    rewards:
        '0':
            type: money
            money: 150
```
