### ISSUE TITLE
Npc respawn: not effect Health config

### ISSUE THREAD

**Issue by Oruss7** [CitizensDev/Citizens#1190]
Hello,

```
      health:
        animatedeath: false
        respawnondeath: false
        respawndelayinseconds: 60s
        respawnlocation: <npc.flag[respawn_location] || <npc.location>>
```
Still unchanged after settings NPC respawn time to -1...
Must change it from config file ='(

Thanks
