### ISSUE TITLE
Hunt quests still broken?

### ISSUE THREAD

**Issue by gjdawson** [CitizensDev/Citizens#224]
The following config for a hunt quest doesn't seem to work:

```
crumbshelmet:
    texts:
        description: A bally creeper bally well ate my favourite helmet and I want revenge! Kill some for me will you?
        acceptance: Marvelous! I'd do it myself, but this armour is just out of the polisher's and I wouldn't want to scuff it. <br>Kill me some creepers!
        completion: Wonderful! Frankly those creepers creep me out. Now I can sleep easy knowing my helmet has been avenged.
    repeats: -1
    objectives:
        '0':
            '0':
                type: hunt
                amount: 1
                string: 'creeper'

    rewards:
        '0':
            type: money
            money: 200
            take: false
```

I'm assuming I got something wrong. No errors show up anywhere, it just doesn't seem to work...

Thanks again guys.

**Comment by fullwall** [comment]
Hm... that should work... I'll look into it.

**Comment by ggirelli** [comment]
Try this:

```
crumbshelmet:
    texts:
        description: "A bally creeper bally well ate my favourite helmet and I want revenge! Kill some for me will you?"
        acceptance: "Marvelous! I'd do it myself, but this armour is just out of the polisher's and I wouldn't want to scuff it.<br>Kill me some creepers!"
        completion: "Wonderful! Frankly those creepers creep me out. Now I can sleep easy knowing my helmet has been avenged."
    repeats: -1
    objectives:
        '0':
            '0':
                type: hunt
                string: 'creeper'
                amount: 1
    rewards:
        '0':
            type: money
            money: 200
            take: false
```
