### ISSUE TITLE
Quests: Only completing the first objective?

### ISSUE THREAD

**Issue by gjdawson** [CitizensDev/Citizens#257]
When I make a quest with more than one objective, the quest completes once all the steps of the first objective are completed and never moves on to the next objective. Unless I've completely misunderstood the documentation, this should work:

```
librariangift:
    texts:
        description: Selling a thing I gave you
        completion: That's the ticket! Gimme my money!
        acceptance: You can find Stan just down the road. Say hi for me!
    repeats: -1
    objectives:
        '0':
            '0':
                type: move location
                location:
                    x: -426
                    y: 69
                    z: 68
                    world: world
                amount: 6
                message: Don't forget to take this stone.
                rewards:
                    '0':
                        type: item
                        id: 4
                        amount: 64
                        take: false
            '1':
                type: delivery
                npcdestination: 5
                materialid: 4
                amount: 64
                message: marvelous!
                rewards:
                    '0':
                        type: money
                        money: 10
                        take: false
        '1':
            '0':
                type: move location
                location:
                    x: -432
                    y: 69
                    z: 62
                    world: world
                amount: 3
                message: You are there!
            '1':
                type: move location
                location:
                    x: -442
                    y: 69
                    z: 68
                    world: world
                amount: 3
                message: You are there too!
```
