### ISSUE TITLE
Quester - Commands reward issue

### ISSUE THREAD

**Issue by d00ba** [CitizensDev/Citizens#531]
The commands reward will only issue the command, if the player that completed the quest has permissions to the command themselves.

**Comment by fullwall** [comment]
server: true executes the command from the server. There isn't much of a way around this unfortunately :/.

**Comment by d00ba** [comment]
I tried using this as a workaround, seemed to work OK.

```
rewards:
    '0':
        type: permission
        permission: commandbook.broadcast
    '1':
        type: command
        command: broadcast <player> completed the Library quest
    '2':
        type: permission
        permission: -commandbook.broadcast 
```

Edit: Though if something goes wrong, the player could end up with a dangerous permission, so not sure if this is a good way to go about it.
