### ISSUE TITLE
No quest money rewards

### ISSUE THREAD

**Issue by xickle** [CitizensDev/Citizens#606]
I have noticed that NPCs don't reward money to players when the quest is completed.
Using BOSEconomy and latest recommended citizens, bukkit and register.

I would set up a command to give money but it needs a player name, like this:  /econ give <playername> <amount>.
I don't know how to insert the player name into the awarded command so it would give, all who complete the quest, the money.

**Comment by Farwaykorse** [comment]
I can't find the excistance of the /econ give command on http://dev.bukkit.org/server-mods/boseconomy/pages/commands/
But I expect you meant: /econ add [playername] [amount]

In a quest this would result in:

```
rewards:
    '0': 
        type: command
        command: econ add <player> 12
        server: false
```

Other values you can use are:

```
# <h>     : player health
# <player>: player name
# <world> : player world
# <npc>   : npc name
# <npcid> : npc id
```
