### ISSUE TITLE
Pigs count as pigmen in hunt quest

### ISSUE THREAD

**Issue by xickle** [CitizensDev/Citizens#612]
I've noticed that killing pigs actually counts as killing pigmen, but not the other way around.
My members can't finish a quest because they kill pigs, which count as pigmen, but they can't get the pig kills done.

My config:

```
objectives:
    '0':
        '0':
            type: hunt
            string: 'pigzombie'
            amount: 5
            optional: False
            finishhere: False
            message: "kill pigmen"

        '1':
            type: hunt
            string: 'pig'
            amount: 10
            optional: False
            finishhere: False
            message: "kill pigs"
```
