### ISSUE TITLE
Move Location not working..

### ISSUE THREAD

**Issue by morizuki** [CitizensDev/Citizens#648]
I'm having a problem on a basic quest of Move Location..  using 1.1.3 Citizens and 1597RB

```
objectives:
        '0':
            '0':
                type: move location
                location:
                    - x: -3 
                    - y: 59
                    - z: -1203
                world: 'world_test'
                amount: 0
                message: Now you are out, deliver this item to George from 2nd floor Town Square

07:17 AM [SEVERE] java.lang.NullPointerException 
07:17 AM [SEVERE] at net.citizensnpcs.utils.StringUtils.format(StringUtils.java:258) 
07:17 AM [SEVERE] at net.citizensnpcs.questers.quests.types.LocationQuest.getStatus(LocationQuest.java:78) 
07:17 AM [SEVERE] at net.citizensnpcs.questers.QuesterCommands.viewCurrentQuestStatus(QuesterCommands.java:438) 
07:17 AM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
07:17 AM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
07:17 AM [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
07:17 AM [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source) 
07:17 AM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530) 
07:17 AM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407) 
07:17 AM [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:200) 
07:17 AM [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40) 
07:17 AM [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) 
07:17 AM [SEVERE] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:378) 
07:17 AM [SEVERE] at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757) 
07:17 AM [SEVERE] at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722) 
07:17 AM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715) 
07:17 AM [SEVERE] at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:180) 
07:17 AM [SEVERE] at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
07:17 AM [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
07:17 AM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93) 
07:17 AM [SEVERE] at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550) 
07:17 AM [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
07:17 AM [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527) 
07:17 AM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425) 
07:17 AM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
```

**Comment by Farwaykorse** [comment]
Try leaving the - , before the x, y and z, away.

**Comment by ghost** [comment]
I see this same error.

```
    '0':
        '0':   
            type: move location   # Specifies loaction objective.
            location:
            x: 310       # Coordinates of location required to visit.
            y: 65
            z: 357
            world: 'world'
            time: 10         # The time (in seconds) that the player has to stay in this location for.
            leeway: 5        # The leeway in blocks that the player can be away from the location before finishing.
```
