### ISSUE TITLE
type: command

### ISSUE THREAD

**Issue by abbacab** [CitizensDev/Citizens#724]
my quest looks like this...

"magus1":
    texts:
        description: "<g>Select a class: <y> Type /hero paths to see a list of classes."
        acceptance: "Type /hero choose to choose your class."
        completion: "Off you go."
    repeats: 0
    delay: 1440
    objectives:
        '0':
            '0':
                type: command
                command: /hero choose cleric,warrior,rogue,wizard,

```
rewards:
    '0':
        server: true
        type: command
        command: tp -258,73,250       
    '1':
        type: command    
        command: xp <player> 50   
        server: true
```

my error is:
12:04:26 AM [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getPlayer()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
    at net.citizensnpcs.resources.npclib.PathNPC.isHoldingBow(PathNPC.java:171)
    at net.citizensnpcs.resources.npclib.PathNPC.isWithinAttackRange(PathNPC.java:182)
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:327)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:206)
    at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:84)
    at net.citizensnpcs.TickTask.run(TickTask.java:30)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
