### ISSUE TITLE
Rank requirements for Quester

### ISSUE THREAD

**Issue by luigivampa** [CitizensDev/Citizens#747]
How do you set the requirements in quest.yml so that a rank needs to be one OR the other.
I have permission groups of wardens and mobsters all of varying seniority. How is the quest.yml configured so that 

```
requirements:
    '0':
        type: rank
        rank: 'mobster'
```

can be

```
requirements:
    '0':
        type: rank
        rank: 'mobster'

       OR

        type: rank
        rank: 'capo'

       OR

        type: rank
        rank: 'boss'
```
